language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - ree
script: bundle exec rspec spec --profile -f d -c
before_install:
  - gem update bundler
install:
  - bundle install --without development
before_script:
  - bundle exec gem list
